### ISSUE TITLE
Validate the ownership of draws against previous versions

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#103]
When a POST arrives, we automatically set the person who is doing it as owner of the draw. When there are previous versions of the draw we should check if the owner is the same. If not when spectating a public draw, anyone can edit the html code enable or add a submit button and become owner of the draw!

**Comment by Mariocj89** [comment]
If you change the owner of a draw it creates a new draw.
Feel free to test it by yourself
https://github.com/etcaterva/EchaloASuerte/blob/master/web/views.py#L62
