### ISSUE TITLE
Users are asked for password in their own draws

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#162]
When joining a draw there are two tables, if the user clicks on the one that shows the column "password", they will be asked for it, but they will be logged in, no matter if the password is right or not

**Comment by Mariocj89** [comment]
I just reproduced it. It is not a bug but totally acceptable. The solution will actually be to remove items from the second table if they are present in the first, there is no point to show draws in both tables.

**Comment by Mariocj89** [comment]
Duplicated: #132
