### ISSUE TITLE
Fix shared config update

### ISSUE THREAD

**Issue by Mariocj89** [etcaterva/EchaloASuerte#260]
When displaying a draw, shared config options dont get updated.

**Comment by dnaranjo89** [comment]
What exactly doesn't update?

**Comment by Mariocj89** [comment]
shared type or users

**Comment by dnaranjo89** [comment]
The emails is not done, I'll fix it tomorrow.
Regarding the shared type:
1) access a public draw,
2) change it from everyone to only with invitation
3) leave the draw
4) access again, an the config is changed

Note that if you change from everyone to password mode and you don't set any password, the shared type will remain "everryone"
