### ISSUE TITLE
Implement WS to send a suggestion

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#282]
Parameters to receive:
 - Suggestion_type: suggestion, bug..
 - Comment: The suggestion itself
 - Browser version:
 - Email: Optional. In case they want us to contact them for further information

Any other thing that we should add?

**Comment by Mariocj89** [comment]
Shoulf we save it In db or send it to the site admins by Mail?

**Comment by dnaranjo89** [comment]
I think an email would be better.
