### ISSUE TITLE
Raffle draw

### ISSUE THREAD

**Issue by Mariocj89** [etcaterva/EchaloASuerte#344]
Draw which the result is one of the connected users.
This issue requires also to track who is connected to a draw.

**Comment by Mariocj89** [comment]
We should be able to import participants from pages or friends in facebook

**Comment by Mariocj89** [comment]
We can make the draw using emails and or facebook (a like button for the draw).

**Comment by Mariocj89** [comment]
We cannot get the list of people who like a page, but we could just record the ids of the people who subscribe to the draw and then just choose one. using the graph api we can display name, photo, etc...

**Comment by dnaranjo89** [comment]
We'll use a FB button to register in a raffle. The point is how do we allow two diferent people to register from the same browser. They could always logout from fb, and then they will be asked again for their credentials. But should we make it easier for them?

I think the 'Register in raffle' button should we always shown and enabled. If the user is already register then ask something like...*"You are logged as Cañita Brava and this user is registered, Isn't it you? Log in again"*

**Comment by Mariocj89** [comment]
Log out and log in as new user seems fine. The web is mobile responsive, they can just share the draw through whatsup and hit register.

**Comment by dnaranjo89** [comment]
@Mariocj89 @palvarez89 Should we use simply 'Login with FB' or 'Share with FB' to participate in a raffle? Or let the user decide when they are creating it?
