### ISSUE TITLE
Improve layour for "choose language" frame

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#36]

**Comment by Mariocj89** [comment]
@dnaranjo89  can you please detail this issue? I find the language dropdown fine.
Note that language is automatically infered from user browser config, and therefore user wont usually need to change it

**Comment by dnaranjo89** [comment]
I did change it but forgot to close this issue (8d5148d1dc1c474c791bd0ef179bfc0cd4f8a3c7). So now yes, it's fine
