### ISSUE TITLE
Weird behaviour in ipad in landscape

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#371]
For some reason they only show up when the ipad is in landscape position

- Breadcrumb in ipad has is not filling the frame
- ~~When clicking a draw in the index, only the tooltip appears, but it's necessary a second click to access it~~ (fixed)

**Comment by Mariocj89** [comment]
Second issue is related to tooltip ( #284 ) and the first is not applicable any more
