### ISSUE TITLE
Monitoring turning into SPAM

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#389]
I'm about to mark most of them as read as they arrive. They come too often. 
Could we do a daily report and send individually only the critical such.... the server is down?

**Comment by palvarez89** [comment]
Meh, issues can be only assigned to one?

We have to discuss about it, and I agree, we are going to end up not caring about the notifications from Monit.

**Comment by dnaranjo89** [comment]
All yours! :D

What would you propose?

**Comment by Mariocj89** [comment]
done
