### ISSUE TITLE
Photo draw

### ISSUE THREAD

**Issue by Mariocj89** [etcaterva/EchaloASuerte#41]

**Comment by Mariocj89** [comment]
http://davidwalsh.name/browser-camera

**Comment by dnaranjo89** [comment]
For mobile devices, it's seems that so far access to camera from HTML5 is only compatible in:
 - Android (Opera mobile)
 - Android 4.0+ (Google Chrome)
 - Android MeeGo (Firefox)
 - BlackBerry OS 10 (Blackberry browser)
 - Symbian (Opera mobile)

**Comment by Mariocj89** [comment]
I am aware, but still I think it is a nice feature to have.
Note that the idea is to work over an image, it can be upload as usual
through an input-file, taking it from the camera can be just an option ;)

**Comment by Mariocj89** [comment]
We can use just a ImageField whch from android can be submited through a photo
To preview the image: http://stackoverflow.com/questions/21076248/imagefield-preview-in-crispy-forms-layout
