### ISSUE TITLE
Find solution for translated keywords and description (SEO)

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#413]
When the result of a Google search is PickForMe, the description is in Spanish.

This also happens when you share the link on any social network: http://www.awesomescreenshot.com/image/417781/c14e43d1251a69df712e353906bbc555

**Comment by palvarez89** [comment]
I discovered that all the <meta> info is hardcoded in the base template. Can it be "translated" to different languages on the same way we translate the rest of the website?

I've also found a [Django SEO](http://django-seo.readthedocs.org/) framework, which may allow us to fix this in a better way. Who knows!
