### ISSUE TITLE
Rework public draw creation

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#426]
### 1. Renaming the type of draws
*Public Draw* is not a good name. Seems that by default, is open to everyone. It will be called *Shared Draw*. On the other hand, the *Private Draw* could remain the same or be called *Normal Draw*?

### 2. Change the way users begin to create a Shared Draw
Currently it is necessary to go to the navigation bar and choose `Public Draw` --> `Create Public Draw`.
Check [this screenshot of a new possible alternative](http://www.awesomescreenshot.com/image/504562/9c5f5a9f9d3bd1d95796662f164670de). The dropdown menu to create a public draw would be removed, leaving only the option `Join Public Draw`

### 3. Remove the breadcrumb
Since there won't be any breadcrumb in the index (it would be like the previous screenshot) there are only two steps to show of the breadcrumb.... I don't see that much the reason to keep it... The buttons *Next* and *Back* will be there, so it will be possible to edit the draw, add emails to the invitations, and then come back to the config...But no breadcrumb.

### 4. Remove password protected draws
It simply doesn't make sense. In which case some would publish the URL but not the password? If you still it's useful somehow we can talk about it. I'm just getting tired to type xD

### 5. Reorganize the *Spread* section
The possible privacy levels will be:
* Everyone (the draw is shown in the *Recently created* list
* Only those invited or with the link (it's the default level)
* Only invited

The option of "Show draw in the list of Recently created" will disappear as it comes implicit in the `Everyone` option.

**Comment by Mariocj89** [comment]
After discussion:
- Remove all kind of protections in public draws. Neither password nor invite only
- Remove list public draw from index

**Comment by Mariocj89** [comment]
done in dev
