### ISSUE TITLE
Don't allow to add messages to chat when chat is disabled

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#526]
Currently can be used by manually remove the ```hidden``` CSS class

**Comment by Mariocj89** [comment]
What is the potential issue of this?

**Comment by dnaranjo89** [comment]
Avoid using the chat when the owner decide not to allow using the chat. Fair enough I guess xD

And it's only one line of code...

**Comment by Mariocj89** [comment]
Not really an issue, if the chat is disabled messages won't appear and the use case requires the user to access the site in a non specified way
