### ISSUE TITLE
Amigo invisible Draw

### ISSUE THREAD

**Issue by Mariocj89** [etcaterva/EchaloASuerte#599]
New draw for the "amigo invisible" se need to check how is this In english

**Comment by dnaranjo89** [comment]
It's the 'secret santa' in English if I'm right...

**Comment by Mariocj89** [comment]
This is actually an interesting draw because we should no display the resultado bit nust send it by email. And not the whole resultado, but a different one pero user

**Comment by koletzilla** [comment]
+1

**Comment by Mariocj89** [comment]
This just don't really fit in echaloasuerte. It might be even easier to build it in a different page
