### ISSUE TITLE
Virtuale enviroment in Server

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#6]
Actually, clean EVERYTHING there and keep the new environment isolated

**Comment by Mariocj89** [comment]
@palvarez89 isnt this done already?

**Comment by palvarez89** [comment]
It is. I had to change the .wgsi file manually to support it. The environment now is isolated except pytz and pymongo. I found some problems with them.

**Comment by Mariocj89** [comment]
Remaining:
 - echaloasuerte.wsgi should check for env variable to get the venv path
 - echaloasuerte.wsgi in etcaterva ansible not neede
 - Add venv path in apache file for echaloasuerte vps

**Comment by palvarez89** [comment]
This is more complex than this. AFAICT, django is not getting the environment set in the Apache configuration file.
