### ISSUE TITLE
Can't toss more than twice

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/EchaloASuerte#612]
To reproduce it:
- Open https://dev.echaloasuerte.com/
- Pick a draw
- Toss
- Toss
- Toss.. oh well, why cannot I do it again?

**Comment by Mariocj89** [comment]
From the console:

`PublicDraw.check_draw_changes();`
PublicDraw is not defined

**Comment by dnaranjo89** [comment]
Fixed
