### ISSUE TITLE
Change protocol in links to share draws

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/EchaloASuerte#616]
They should be https or better, gone

**Comment by Mariocj89** [comment]
Please, add more details -_- the title is awful, as the description

**Comment by dnaranjo89** [comment]
Updated,
It was an emergency issue, better this than forgetting it :D

**Comment by palvarez89** [comment]
Is "always redirect to https" an option here?

**Comment by dnaranjo89** [comment]
So, when creating a draw through the API, the response's header has `location=http://echaloasuerte.com/...` instead of https. @Mariocj89 do you know why?

**Comment by Mariocj89** [comment]
Because the site is served in http. Http comes from cloudflare

**Comment by Mariocj89** [comment]
This is a limitation of the "fake" https, there is already a workaround in the js code
